extern crate bindgen;
use std::env;


fn main () {

    println!("cargo:rustc-link-lib=pjlib_util");
    println!("cargo:rustc-link-search=native=/usr/lib");
    println!("cargo:rerun-if-changed=wrapper.h");

    let pjlib_util = bindgen::Builder::default().header("wrapper.h")

        .raw_line("#![allow(non_upper_case_globals)]")
        .raw_line("#![allow(non_camel_case_types)]")
        .raw_line("#![allow(non_snake_case)]")
        .raw_line("extern crate pj_sys;")
        .raw_line("use pj_sys::*;")

        // pj-sys
        // struct
        // .blocklist_item("pj_str_t")
        // .blocklist_item("pj_timestamp__bindgen_ty_1")
        // .blocklist_item("pj_hash_table_t")
        // .blocklist_item("pj_hash_entry")
        // .blocklist_item("pj_hash_iterator_t")
        // .blocklist_item("pj_ioqueue_t")
        // .blocklist_item("pj_ioqueue_key_t")
        // .blocklist_item("pj_timer_heap_t")
        // .blocklist_item("pj_atomic_t")
        // .blocklist_item("pj_thread_t")
        // .blocklist_item("pj_lock_t")
        // .blocklist_item("pj_grp_lock_t")
        // .blocklist_item("pj_mutex_t")
        // .blocklist_item("pj_sem_t")
        // .blocklist_item("pj_event_t")
        // .blocklist_item("pj_pipe_t")
        // .blocklist_item("pj_time_val")
        // .blocklist_item("pj_parsed_time")
        // .blocklist_item("pj_ioqueue_op_key_t")
        // .blocklist_item("pj_ioqueue_callback")
        // .blocklist_item("__sigset_t")
        // .blocklist_item("in_addr")
        // .blocklist_item("in6_addr")
        // .blocklist_item("pj_sockaddr_in")
        // .blocklist_item("pj_sockaddr_in6")
        // .blocklist_item("pj_addr_hdr")
        // .blocklist_item("pj_ip_mreq")
        // .blocklist_item("pj_sockopt_params")
        // .blocklist_item("pj_sockopt_params__bindgen_ty_1")
        // .blocklist_item("pj_activesock_t")
        // .blocklist_item("pj_activesock_cb")
        // .blocklist_item("pj_activesock_cfg")
        // .blocklist_item("pj_hostent")
        // .blocklist_item("pj_addrinfo")
        // .blocklist_item("__jmp_buf_tag")
        // .blocklist_item("pj_exception_state_t")
        // .blocklist_item("pj_fifobuf_t")
        // .blocklist_item("pj_file_stat")
        // .blocklist_item("pj_ip_route_entry__bindgen_ty_1")
        // .blocklist_item("pj_enum_ip_option")
        // .blocklist_item("pj_list")
        // .blocklist_item("pj_grp_lock_config")
        // .blocklist_item("pj_math_stat")
        // .blocklist_item("pj_sys_info")
        // .blocklist_item("pj_symbianos_params")
        // .blocklist_item("pj_rwmutex_t")
        // .blocklist_item("pj_pool_block")
        // .blocklist_item("pj_pool_t")
        // .blocklist_item("pj_pool_factory_policy")
        // .blocklist_item("pj_pool_factory")
        // .blocklist_item("pj_caching_pool")
        // .blocklist_item("pj_rbtree_node")
        // .blocklist_item("pj_rbtree")
        // .blocklist_item("pj_qos_params")
        // .blocklist_item("pj_fd_set_t")
        // .blocklist_item("pj_ssl_sock_t")
        // .blocklist_item("pj_ssl_cert_t")
        // .blocklist_item("pj_ssl_cert_info")
        // .blocklist_item("pj_ssl_cert_info__bindgen_ty_1")
        // .blocklist_item("pj_ssl_cert_info__bindgen_ty_2")
        // .blocklist_item("pj_ssl_cert_info__bindgen_ty_3")
        // .blocklist_item("pj_ssl_cert_info__bindgen_ty_4")
        // .blocklist_item("pj_ssl_cert_info__bindgen_ty_4__bindgen_ty_1")
        // .blocklist_item("pj_ssl_cert_info__bindgen_ty_5")
        // .blocklist_item("pj_ssl_sock_cb")
        // .blocklist_item("pj_ssl_sock_info")
        // .blocklist_item("pj_ssl_sock_param")
        // .blocklist_item("pj_ssl_start_connect_param")
        // .blocklist_item("pj_timer_entry")
        // .blocklist_item("__va_list_tag")

        // // pj-sys
        // // type
        // .blocklist_item("pj_int64_t")
        // .blocklist_item("pj_uint64_t")
        // .blocklist_item("size_t")
        // .blocklist_item("pj_int32_t")
        // .blocklist_item("pj_uint32_t")
        // .blocklist_item("pj_int16_t")
        // .blocklist_item("pj_uint16_t")
        // .blocklist_item("pj_int8_t")
        // .blocklist_item("pj_uint8_t")
        // .blocklist_item("pj_size_t")
        // .blocklist_item("pj_ssize_t")
        // .blocklist_item("pj_status_t")
        // .blocklist_item("pj_bool_t")
        // .blocklist_item("pj_char_t")
        // .blocklist_item("pj_constants_")
        // .blocklist_item("pj_off_t")
        // .blocklist_item("pj_list_type")
        // .blocklist_item("pj_atomic_value_t")
        // .blocklist_item("pj_oshandle_t")
        // .blocklist_item("pj_sock_t")
        // .blocklist_item("pj_sockaddr_t")
        // .blocklist_item("pj_color_t")
        // .blocklist_item("pj_exception_id_t")
        // .blocklist_item("pj_exit_callback")
        // .blocklist_item("pj_ioqueue_operation_e")
        // .blocklist_item("__uint8_t")
        // .blocklist_item("__uint16_t")
        // .blocklist_item("__uint32_t")
        // .blocklist_item("in_addr_t")
        // .blocklist_item("pj_socket_sd_type")
        // .blocklist_item("pj_in_addr")
        // .blocklist_item("pj_in6_addr")
        // .blocklist_item("pj_os_err_type")
        // .blocklist_item("va_list")
        // .blocklist_item("pj_error_callback")
        // .blocklist_item("__jmp_buf")
        // .blocklist_item("jmp_buf")
        // .blocklist_item("pj_jmp_buf")
        // .blocklist_item("pj_log_decoration")
        // .blocklist_item("pj_log_func")
        // .blocklist_item("pj_file_access")
        // .blocklist_item("pj_file_seek_type")
        // .blocklist_item("pj_hash_entry_buf")
        // .blocklist_item("pj_highprec_t")
        // .blocklist_item("pj_sys_info_flag")
        // .blocklist_item("pj_thread_create_flags")
        // .blocklist_item("pj_thread_proc")
        // .blocklist_item("pj_thread_desc")
        // .blocklist_item("pj_mutex_type_e")
        // .blocklist_item("pj_main_func_ptr")
        // .blocklist_item("pj_pool_callback")
        // .blocklist_item("pj_rbcolor_t")
        // .blocklist_item("pj_rbtree_comp")
        // .blocklist_item("pj_qos_type")
        // .blocklist_item("pj_qos_flag")
        // .blocklist_item("pj_qos_wmm_prio")
        // .blocklist_item("pj_ssl_cert_verify_flag_t")
        // .blocklist_item("pj_ssl_cert_name_type")
        // .blocklist_item("pj_ssl_cert_buffer")
        // .blocklist_item("pj_ssl_cipher")
        // .blocklist_item("pj_ssl_curve")
        // .blocklist_item("pj_ssl_entropy")
        // .blocklist_item("pj_ssl_sock_proto")
        // .blocklist_item("pj_timer_id_t")
        // .blocklist_item("pj_timer_heap_callback")
        // .blocklist_item("__builtin_va_list")

        // // pj-sys
        // // pub static
        // .blocklist_item("PJ_VERSION")
        // .blocklist_item("PJ_AF_UNSPEC")
        // .blocklist_item("PJ_AF_UNIX")
        // .blocklist_item("PJ_AF_INET")
        // .blocklist_item("PJ_AF_INET6")
        // .blocklist_item("PJ_AF_PACKET")
        // .blocklist_item("PJ_AF_IRDA")
        // .blocklist_item("PJ_SOCK_STREAM")
        // .blocklist_item("PJ_SOCK_DGRAM")
        // .blocklist_item("PJ_SOCK_RAW")
        // .blocklist_item("PJ_SOCK_RDM")
        // .blocklist_item("PJ_SOL_SOCKET")
        // .blocklist_item("PJ_SOL_IP")
        // .blocklist_item("PJ_SOL_TCP")
        // .blocklist_item("PJ_SOL_UDP")
        // .blocklist_item("PJ_SOL_IPV6")
        // .blocklist_item("PJ_IP_TOS")
        // .blocklist_item("PJ_IPTOS_LOWDELAY")
        // .blocklist_item("PJ_IPTOS_THROUGHPUT")
        // .blocklist_item("PJ_IPTOS_RELIABILITY")
        // .blocklist_item("PJ_IPTOS_MINCOST")
        // .blocklist_item("PJ_IPV6_TCLASS")
        // .blocklist_item("PJ_SO_TYPE")
        // .blocklist_item("PJ_SO_RCVBUF")
        // .blocklist_item("PJ_SO_SNDBUF")
        // .blocklist_item("PJ_TCP_NODELAY")
        // .blocklist_item("PJ_SO_REUSEADDR")
        // .blocklist_item("PJ_SO_NOSIGPIPE")
        // .blocklist_item("PJ_SO_PRIORITY")
        // .blocklist_item("PJ_IP_MULTICAST_IF")
        // .blocklist_item("PJ_IP_MULTICAST_TTL")
        // .blocklist_item("PJ_IP_MULTICAST_LOOP")
        // .blocklist_item("PJ_IP_ADD_MEMBERSHIP")
        // .blocklist_item("PJ_IP_DROP_MEMBERSHIP")
        // .blocklist_item("PJ_MSG_OOB")
        // .blocklist_item("PJ_MSG_PEEK")
        // .blocklist_item("PJ_MSG_DONTROUTE")
        // .blocklist_item("PJ_GUID_STRING_LENGTH")
        // .blocklist_item("pj_pool_factory_default_policy")

        .allowlist_function("pj_base64_decode")
        .allowlist_function("pj_base64_encode")
        .allowlist_type("PJ_BASE64_.*")
        .allowlist_type("pj_base64_.*")

        .allowlist_function("pj_cli_add_cmd_from_xml")
        .allowlist_function("pj_cli_cfg_default")
        .allowlist_function("pj_cli_console_cfg_default")
        .allowlist_function("pj_cli_console_create")
        .allowlist_function("pj_cli_console_process")
        .allowlist_function("pj_cli_create")
        .allowlist_function("pj_cli_destroy")
        .allowlist_function("pj_cli_exec_info_default")
        .allowlist_function("pj_cli_get_cmd_id")
        .allowlist_function("pj_cli_get_param")
        .allowlist_function("pj_cli_is_quitting")
        .allowlist_function("pj_cli_is_restarting")
        .allowlist_function("pj_cli_quit")
        .allowlist_function("pj_cli_register_front_end")
        .allowlist_function("pj_cli_sess_end_session")
        .allowlist_function("pj_cli_sess_exec")
        .allowlist_function("pj_cli_sess_parse")
        .allowlist_function("pj_cli_sess_write_msg")
        .allowlist_function("pj_cli_telnet_cfg_default")
        .allowlist_function("pj_cli_telnet_create")
        .allowlist_function("pj_cli_telnet_get_info")
        .allowlist_function("pj_cli_write_log")
        .allowlist_type("PJ_CLI.*")
        .allowlist_type("pj_cli.*")
        .allowlist_var("PJ_CLI.*")
        .allowlist_var("pj_cli.*")


        .allowlist_function("pj_crc32_calc")
        .allowlist_function("pj_crc32_final")
        .allowlist_function("pj_crc32_init")
        .allowlist_function("pj_crc32_update")
        .allowlist_type("PJ_CRC32_.*")
        .allowlist_type("pj_crc32_.*")

        .allowlist_function("pj_dns_dump_packet")
        .allowlist_function("pj_dns_get_type_name")
        .allowlist_function("pj_dns_init_aaaa_rr")
        .allowlist_function("pj_dns_init_a_rr")
        .allowlist_function("pj_dns_init_cname_rr")
        .allowlist_function("pj_dns_init_srv_rr")
        .allowlist_function("pj_dns_make_query")
        .allowlist_function("pj_dns_packet_dup")
        .allowlist_function("pj_dns_parse_addr_response")
        .allowlist_function("pj_dns_parse_a_response")
        .allowlist_function("pj_dns_parse_packet")
        .allowlist_function("pj_dns_resolver_add_entry")
        .allowlist_function("pj_dns_resolver_cancel_query")
        .allowlist_function("pj_dns_resolver_create")
        .allowlist_function("pj_dns_resolver_destroy")
        .allowlist_function("pj_dns_resolver_dump")
        .allowlist_function("pj_dns_resolver_get_cached_count")
        .allowlist_function("pj_dns_resolver_get_settings")
        .allowlist_function("pj_dns_resolver_handle_events")
        .allowlist_function("pj_dns_resolver_set_ns")
        .allowlist_function("pj_dns_resolver_set_settings")
        .allowlist_function("pj_dns_resolver_start_query")
        .allowlist_function("pj_dns_server_add_rec")
        .allowlist_function("pj_dns_server_create")
        .allowlist_function("pj_dns_server_del_rec")
        .allowlist_function("pj_dns_server_destroy")
        .allowlist_function("pj_dns_settings_default")
        .allowlist_function("pj_dns_srv_cancel_query")
        .allowlist_function("pj_dns_srv_resolve")
        .allowlist_type("PJ_DNS_.*")
        .allowlist_type("pj_dns_.*")

        .allowlist_function("pj_getopt")
        .allowlist_function("pj_getopt_long")
        .allowlist_type("PJ_GETOPT_.*")
        .allowlist_type("pj_getopt_.*")

        .allowlist_function("pj_hmac_md5")
        .allowlist_function("pj_hmac_md5_final")
        .allowlist_function("pj_hmac_md5_init")
        .allowlist_function("pj_hmac_md5_update")
        .allowlist_type("PJ_HMAC_MD5_.*")
        .allowlist_type("pj_hmac_md5_.*")

        .allowlist_function("pj_hmac_sha1")
        .allowlist_function("pj_hmac_sha1_final")
        .allowlist_function("pj_hmac_sha1_init")
        .allowlist_function("pj_hmac_sha1_update")
        .allowlist_type("PJ_HMAC_SHA1_.*")
        .allowlist_type("pj_hmac_sha1_.*")

        .allowlist_function("pj_http_headers_add_elmt")
        .allowlist_function("pj_http_headers_add_elmt2")
        .allowlist_function("pj_http_req_cancel")
        .allowlist_function("pj_http_req_create")
        .allowlist_function("pj_http_req_destroy")
        .allowlist_function("pj_http_req_get_user_data")
        .allowlist_function("pj_http_req_is_running")
        .allowlist_function("pj_http_req_param_default")
        .allowlist_function("pj_http_req_parse_url")
        .allowlist_function("pj_http_req_set_timeout")
        .allowlist_function("pj_http_req_start")
        .allowlist_type("PJ_HTTP.*")
        .allowlist_type("pj_http.*")
        .allowlist_var("PJ_HTTP.*")
        .allowlist_var("pj_http.*")

        .allowlist_function("pj_json_elem_add")
        .allowlist_function("pj_json_elem_array")
        .allowlist_function("pj_json_elem_bool")
        .allowlist_function("pj_json_elem_null")
        .allowlist_function("pj_json_elem_number")
        .allowlist_function("pj_json_elem_obj")
        .allowlist_function("pj_json_elem_string")
        .allowlist_function("pj_json_parse")
        .allowlist_function("pj_json_write")
        .allowlist_function("pj_json_writef")
        .allowlist_type("PJ_JSON.*")
        .allowlist_type("pj_json.*")
        .allowlist_var("PJ_JSON.*")
        .allowlist_var("pj_json.*")

        .allowlist_function("pjlib_util_init")
        .allowlist_function("pjlib_util_strerror")
        .allowlist_type("PJLIB_UTIL.*")
        .allowlist_type("pjlib_util.*")
        .allowlist_var("PJLIB_UTIL.*")
        .allowlist_var("pjlib_util.*")

        .allowlist_function("pj_md5_final")
        .allowlist_function("pj_md5_init")
        .allowlist_function("pj_md5_update")
        .allowlist_type("PJ_MD5_.*")
        .allowlist_type("pj_md5_.*")

        .allowlist_function("pj_pcap_close")
        .allowlist_function("pj_pcap_filter_default")
        .allowlist_function("pj_pcap_open")
        .allowlist_function("pj_pcap_read_udp")
        .allowlist_function("pj_pcap_set_filter")
        .allowlist_type("PJ_PCAP_.*")
        .allowlist_type("pj_pcap_.*")

        .allowlist_function("pj_cis_add_alpha")
        .allowlist_function("pj_cis_add_cis")
        .allowlist_function("pj_cis_add_num")
        .allowlist_function("pj_cis_add_range")
        .allowlist_function("pj_cis_add_str")
        .allowlist_function("pj_cis_buf_init")
        .allowlist_function("pj_cis_del_range")
        .allowlist_function("pj_cis_del_str")
        .allowlist_function("pj_cis_dup")
        .allowlist_function("pj_cis_init")
        .allowlist_function("pj_cis_invert")
        .allowlist_type("PJ_CIS.*")
        .allowlist_type("pj_cis.*")
        .allowlist_var("pj_cis.*")

        .allowlist_function("pj_scan_advance_n")
        .allowlist_function("pj_scan_fini")
        .allowlist_function("pj_scan_get")
        .allowlist_function("pj_scan_get_char")
        .allowlist_function("pj_scan_get_n")
        .allowlist_function("pj_scan_get_newline")
        .allowlist_function("pj_scan_get_quote")
        .allowlist_function("pj_scan_get_quotes")
        .allowlist_function("pj_scan_get_unescape")
        .allowlist_function("pj_scan_get_until")
        .allowlist_function("pj_scan_get_until_ch")
        .allowlist_function("pj_scan_get_until_chr")
        .allowlist_function("pj_scan_init")
        .allowlist_function("pj_scan_peek")
        .allowlist_function("pj_scan_peek_n")
        .allowlist_function("pj_scan_peek_until")
        .allowlist_function("pj_scan_restore_state")
        .allowlist_function("pj_scan_save_state")
        .allowlist_function("pj_scan_skip_line")
        .allowlist_function("pj_scan_skip_whitespace")
        .allowlist_function("pj_scan_strcmp")
        .allowlist_function("pj_scan_stricmp")
        .allowlist_function("pj_scan_stricmp_alnum")
        .allowlist_type("pj_syn_err_func_ptr")
        .allowlist_type("PJ_SCAN.*")
        .allowlist_type("pj_scan.*")
        .allowlist_var("PJ_SCAN.*")
        .allowlist_var("pj_scan.*")

        .allowlist_function("pj_sha1_final")
        .allowlist_function("pj_sha1_init")
        .allowlist_function("pj_sha1_update")
        .allowlist_type("PJ_SHA1_.*")
        .allowlist_type("pj_sha1_.*")

        .allowlist_function("pj_strcpy_unescape")
        .allowlist_function("pj_strncpy2_escape")
        .allowlist_function("pj_strncpy_escape")
        .allowlist_function("pj_str_unescape")

        .allowlist_function("pjstun_create_bind_req")
        .allowlist_function("pjstun_get_mapped_addr")
        .allowlist_function("pjstun_get_mapped_addr2")
        .allowlist_function("pjstun_msg_find_attr")
        .allowlist_function("pjstun_parse_msg")
        .allowlist_type("PJSTUN_.*")
        .allowlist_type("pjstun_.*")

        .allowlist_function("pj_xml_add_attr")
        .allowlist_function("pj_xml_add_node")
        .allowlist_function("pj_xml_attr_new")
        .allowlist_function("pj_xml_clone")
        .allowlist_function("pj_xml_find")
        .allowlist_function("pj_xml_find_attr")
        .allowlist_function("pj_xml_find_next_node")
        .allowlist_function("pj_xml_find_node")
        .allowlist_function("pj_xml_find_node_rec")
        .allowlist_function("pj_xml_find_rec")
        .allowlist_function("pj_xml_node_new")
        .allowlist_function("pj_xml_parse")
        .allowlist_function("pj_xml_print")
        .allowlist_type("PJ_XML_.*")
        .allowlist_type("pj_xml_.*")

        .allowlist_var("arg_type")
        .allowlist_var("pj_optind")
        .allowlist_var("pj_optopt")

        // .allowlist_type("PJ_.*")
        // .allowlist_type("pj_.*")

        .allowlist_recursively(false)
        .translate_enum_integer_types(true)
        .layout_tests(false)
        .prepend_enum_name(false)
        .generate()
        // Unwrap the Result and panic on failure.
        .expect("Unable to generate bindings");

    // Write the bindings to the $OUT_DIR/bindings.rs file.
    let out_path = env::current_dir().unwrap();
    pjlib_util.write_to_file(out_path.join("src/lib.rs")).expect("Error write src/lib.rs");

}
