[package]
name = "open_audio_ip_codec"
version = "0.1.0"
authors = ["tamara"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pj-sys = { path = "./pj-sys" }
pjsua-sys = { path = "./pjsua-sys" }

[build-dependencies]
