
extern crate bindgen;
use std::env;

fn main () {

    println!("cargo:rustc-link-lib=pjsip-simple");
    println!("cargo:rustc-link-search=native=/usr/lib");
    println!("cargo:rerun-if-changed=wrapper.h");

    // The bindgen::Builder is the main entry point
    // to bindgen, and lets you build up options for
    // the resulting bindings.
    let pjsip_simple = bindgen::Builder::default().header("wrapper.h")

        .raw_line("#![allow(non_upper_case_globals)]")
        .raw_line("#![allow(non_camel_case_types)]")
        .raw_line("#![allow(non_snake_case)]")
        .raw_line("extern crate pj_sys;")
        .raw_line("extern crate pjlib_util_sys;")
        .raw_line("use pj_sys::*;")
        .raw_line("use pjlib_util_sys::*;")
        // .parse_callbacks(Box::new(bindgen::CargoCallbacks))

               // pj-sys
        // struct
        .blocklist_type("pj_timestamp").blocklist_type("pj_sockaddr").blocklist_type("pj_str_t").blocklist_type("pj_timestamp__bindgen_ty_1")
        .blocklist_type("pj_hash_table_t").blocklist_type("pj_hash_entry").blocklist_type("pj_hash_iterator_t").blocklist_type("pj_ioqueue_t")
        .blocklist_type("pj_ioqueue_key_t").blocklist_type("pj_timer_heap_t").blocklist_type("pj_atomic_t").blocklist_type("pj_thread_t")
        .blocklist_type("pj_lock_t").blocklist_type("pj_grp_lock_t").blocklist_type("pj_mutex_t").blocklist_type("pj_sem_t")
        .blocklist_type("pj_event_t").blocklist_type("pj_pipe_t").blocklist_type("pj_time_val").blocklist_type("pj_parsed_time")
        .blocklist_type("pj_ioqueue_op_key_t").blocklist_type("pj_ioqueue_callback").blocklist_type("__sigset_t").blocklist_type("in_addr.*")
        .blocklist_type("in6_addr.*").blocklist_type("pj_sockaddr_in").blocklist_type("pj_sockaddr_in6").blocklist_type("pj_addr_hdr")
        .blocklist_type("pj_ip_mreq").blocklist_type("pj_sockopt_params").blocklist_type("pj_sockopt_params__bindgen_ty_1").blocklist_type("pj_activesock_t")
        .blocklist_type("pj_activesock_cb").blocklist_type("pj_activesock_cfg").blocklist_type("pj_hostent").blocklist_type("pj_addrinfo")
        .blocklist_type("__jmp_buf_tag").blocklist_type("pj_exception_state_t").blocklist_type("pj_fifobuf_t").blocklist_type("pj_file_stat")
        .blocklist_type("pj_ip_route_entry__bindgen_ty_1").blocklist_type("pj_enum_ip_option").blocklist_type("pj_list").blocklist_type("pj_grp_lock_config")
        .blocklist_type("pj_math_stat").blocklist_type("pj_sys_info").blocklist_type("pj_symbianos_params").blocklist_type("pj_rwmutex_t")
        .blocklist_type("pj_pool_block").blocklist_type("pj_pool_t").blocklist_type("pj_pool_factory_policy").blocklist_type("pj_pool_factory")
        .blocklist_type("pj_caching_pool").blocklist_type("pj_rbtree_node").blocklist_type("pj_rbtree").blocklist_type("pj_qos_params")
        .blocklist_type("pj_fd_set_t").blocklist_type("pj_ssl_sock_t").blocklist_type("pj_ssl_cert_t").blocklist_type("pj_ssl_cert_info")
        .blocklist_type("pj_ssl_cert_info__bindgen_ty_1").blocklist_type("pj_ssl_cert_info__bindgen_ty_2").blocklist_type("pj_ssl_cert_info__bindgen_ty_3").blocklist_type("pj_ssl_cert_info__bindgen_ty_4")
        .blocklist_type("pj_ssl_cert_info__bindgen_ty_4__bindgen_ty_1").blocklist_type("pj_ssl_cert_info__bindgen_ty_5").blocklist_type("pj_ssl_sock_cb").blocklist_type("pj_ssl_sock_info")
        .blocklist_type("pj_ssl_sock_param").blocklist_type("pj_ssl_start_connect_param").blocklist_type("pj_timer_entry").blocklist_type("__va_list_tag")

        // pj-sys
        // type
        .blocklist_type("pj_int64_t").blocklist_type("pj_uint64_t").blocklist_type("size_t").blocklist_type("pj_int32_t").blocklist_type("pj_uint32_t")
        .blocklist_type("pj_int16_t").blocklist_type("pj_uint16_t").blocklist_type("pj_int8_t").blocklist_type("pj_uint8_t").blocklist_type("pj_size_t")
        .blocklist_type("pj_ssize_t").blocklist_type("pj_status_t").blocklist_type("pj_bool_t").blocklist_type("pj_char_t").blocklist_type("pj_constants_")
        .blocklist_type("pj_off_t").blocklist_type("pj_list_type").blocklist_type("pj_atomic_value_t").blocklist_type("pj_oshandle_t").blocklist_type("pj_sock_t")
        .blocklist_type("pj_sockaddr_t").blocklist_type("pj_color_t").blocklist_type("pj_exception_id_t").blocklist_type("pj_exit_callback").blocklist_type("pj_ioqueue_operation_e")
        .blocklist_type("__uint8_t").blocklist_type("__uint16_t").blocklist_type("__uint32_t").blocklist_type("in_addr_t").blocklist_type("pj_socket_sd_type")
        .blocklist_type("pj_in_addr").blocklist_type("pj_in6_addr").blocklist_type("pj_os_err_type").blocklist_type("va_list").blocklist_type("pj_error_callback")
        .blocklist_type("__jmp_buf").blocklist_type("jmp_buf").blocklist_type("pj_jmp_buf").blocklist_type("pj_log_decoration").blocklist_type("pj_log_func")
        .blocklist_type("pj_file_access").blocklist_type("pj_file_seek_type").blocklist_type("pj_hash_entry_buf").blocklist_type("pj_highprec_t").blocklist_type("pj_sys_info_flag")
        .blocklist_type("pj_thread_create_flags").blocklist_type("pj_thread_proc").blocklist_type("pj_thread_desc").blocklist_type("pj_mutex_type_e").blocklist_type("pj_main_func_ptr")
        .blocklist_type("pj_pool_callback").blocklist_type("pj_rbcolor_t").blocklist_type("pj_rbtree_comp").blocklist_type("pj_qos_type").blocklist_type("pj_qos_flag")
        .blocklist_type("pj_qos_wmm_prio").blocklist_type("pj_ssl_cert_verify_flag_t").blocklist_type("pj_ssl_cert_name_type").blocklist_type("pj_ssl_cert_buffer").blocklist_type("pj_ssl_cipher")
        .blocklist_type("pj_ssl_curve").blocklist_type("pj_ssl_entropy").blocklist_type("pj_ssl_sock_proto").blocklist_type("pj_timer_id_t").blocklist_type("pj_timer_heap_callback")
        .blocklist_type("__builtin_va_list")

        // pj-sys
        // pub static
        .blocklist_item("PJ_VERSION").blocklist_item("PJ_AF_UNSPEC").blocklist_item("PJ_AF_UNIX").blocklist_item("PJ_AF_INET").blocklist_item("PJ_AF_INET6")
        .blocklist_item("PJ_AF_PACKET").blocklist_item("PJ_AF_IRDA").blocklist_item("PJ_SOCK_STREAM").blocklist_item("PJ_SOCK_DGRAM").blocklist_item("PJ_SOCK_RAW")
        .blocklist_item("PJ_SOCK_RDM").blocklist_item("PJ_SOL_SOCKET").blocklist_item("PJ_SOL_IP").blocklist_item("PJ_SOL_TCP").blocklist_item("PJ_SOL_UDP")
        .blocklist_item("PJ_SOL_IPV6").blocklist_item("PJ_IP_TOS").blocklist_item("PJ_IPTOS_LOWDELAY").blocklist_item("PJ_IPTOS_THROUGHPUT").blocklist_item("PJ_IPTOS_RELIABILITY")
        .blocklist_item("PJ_IPTOS_MINCOST").blocklist_item("PJ_IPV6_TCLASS").blocklist_item("PJ_SO_TYPE").blocklist_item("PJ_SO_RCVBUF").blocklist_item("PJ_SO_SNDBUF")
        .blocklist_item("PJ_TCP_NODELAY").blocklist_item("PJ_SO_REUSEADDR").blocklist_item("PJ_SO_NOSIGPIPE").blocklist_item("PJ_SO_PRIORITY").blocklist_item("PJ_IP_MULTICAST_IF")
        .blocklist_item("PJ_IP_MULTICAST_TTL").blocklist_item("PJ_IP_MULTICAST_LOOP").blocklist_item("PJ_IP_ADD_MEMBERSHIP").blocklist_item("PJ_IP_DROP_MEMBERSHIP").blocklist_item("PJ_MSG_OOB")
        .blocklist_item("PJ_MSG_PEEK").blocklist_item("PJ_MSG_DONTROUTE").blocklist_item("PJ_GUID_STRING_LENGTH").blocklist_item("pj_pool_factory_default_policy")

        .blocklist_item("pj_ssl_entropy").blocklist_item("pj_ssl_entropy_t")

        // pjnath-sys
        // pub type
        .blocklist_type("pj_stun_method_e").blocklist_type("pj_stun_msg_class_e").blocklist_type("pj_stun_msg_type").blocklist_type("pj_stun_attr_type")
        .blocklist_type("pj_stun_status").blocklist_type("pj_stun_fingerprint_attr").blocklist_type("pj_stun_realm_attr").blocklist_type("pj_stun_nonce_attr")
        .blocklist_type("pj_stun_mapped_addr_attr").blocklist_type("pj_stun_xor_mapped_addr_attr").blocklist_type("pj_stun_software_attr").blocklist_type("pj_stun_alt_server_attr")
        .blocklist_type("pj_stun_refresh_interval_attr").blocklist_type("pj_stun_response_addr_attr").blocklist_type("pj_stun_changed_addr_attr").blocklist_type("pj_stun_change_request_attr")
        .blocklist_type("pj_stun_src_addr_attr").blocklist_type("pj_stun_reflected_from_attr").blocklist_type("pj_stun_username_attr").blocklist_type("pj_stun_password_attr")
        .blocklist_type("pj_stun_channel_number_attr").blocklist_type("pj_stun_lifetime_attr").blocklist_type("pj_stun_bandwidth_attr").blocklist_type("pj_stun_xor_peer_addr_attr")
        .blocklist_type("pj_stun_data_attr").blocklist_type("pj_stun_xor_relayed_addr_attr").blocklist_type("pj_stun_req_addr_type_attr").blocklist_type("pj_stun_even_port_attr")
        .blocklist_type("pj_stun_req_transport_attr").blocklist_type("pj_stun_dont_fragment_attr").blocklist_type("pj_stun_res_token_attr").blocklist_type("pj_stun_xor_reflected_from_attr")
        .blocklist_type("pj_stun_priority_attr").blocklist_type("pj_stun_use_candidate_attr").blocklist_type("pj_stun_timer_val_attr").blocklist_type("pj_stun_ice_controlling_attr")
        .blocklist_type("pj_stun_ice_controlled_attr").blocklist_type("pj_stun_icmp_attr").blocklist_type("pj_stun_decode_options").blocklist_type("pj_stun_auth_type")
        .blocklist_type("pj_stun_auth_cred_type").blocklist_type("pj_stun_passwd_type").blocklist_type("pj_stun_sess_msg_log_flag").blocklist_type("pj_ice_cand_type")
        .blocklist_type("pj_ice_sess_check_state").blocklist_type("pj_ice_sess_checklist_state").blocklist_type("pj_ice_sess_role").blocklist_type("pj_ice_sess_trickle")
        .blocklist_type("pj_dns_rcode").blocklist_type("pj_dns_dup_options").blocklist_type("pj_stun_sock_op").blocklist_type("pj_turn_tp_type")
        .blocklist_type("pj_turn_state_t").blocklist_type("pj_ice_strans_op").blocklist_type("pj_ice_strans_state").blocklist_type("pj_stun_nat_type")
        .blocklist_type("pj_stun_nat_detect_cb")

        // pjnath-sys
        // pub struct
        .blocklist_type("pj_stun_msg_hdr").blocklist_type("pj_stun_attr_hdr").blocklist_type("pj_stun_sockaddr_attr").blocklist_type("pj_stun_empty_attr")
        .blocklist_type("pj_stun_string_attr").blocklist_type("pj_stun_uint_attr").blocklist_type("pj_stun_uint64_attr").blocklist_type("pj_stun_binary_attr")
        .blocklist_type("pj_stun_msgint_attr").blocklist_type("pj_stun_errcode_attr").blocklist_type("pj_stun_unknown_attr").blocklist_type("pj_stun_msg")
        .blocklist_type("pj_stun_auth_cred").blocklist_type("pj_stun_req_cred_info").blocklist_type("pj_stun_config").blocklist_type("pj_stun_client_tsx")
        .blocklist_type("pj_stun_tsx_cb").blocklist_type("pj_stun_session").blocklist_type("pj_stun_session_cb").blocklist_type("pj_stun_rx_data")
        .blocklist_type("pj_stun_tx_data").blocklist_type("pj_ice_sess_comp").blocklist_type("pj_ice_msg_data").blocklist_type("pj_ice_msg_data_data_request_data")
        .blocklist_type("pj_ice_sess_cand").blocklist_type("pj_ice_sess_check").blocklist_type("pj_ice_sess_checklist").blocklist_type("pj_ice_sess_cb")
        .blocklist_type("pj_ice_rx_check").blocklist_type("pj_ice_sess_options").blocklist_type("pj_ice_sess").blocklist_type("pj_dns_hdr")
        .blocklist_type("pj_dns_parsed_query").blocklist_type("pj_dns_parsed_rr").blocklist_type("pj_dns_parsed_rr_rdata").blocklist_type("pj_dns_parsed_rr_rdata_srv")
        .blocklist_type("pj_dns_parsed_rr_rdata_cname").blocklist_type("pj_dns_parsed_rr_rdata_ns").blocklist_type("pj_dns_parsed_rr_rdata_ptr").blocklist_type("pj_dns_parsed_rr_rdata_a")
        .blocklist_type("pj_dns_parsed_rr_rdata_aaaa").blocklist_type("pj_dns_parsed_packet").blocklist_type("pj_dns_resolver").blocklist_type("pj_dns_async_query")
        .blocklist_type("pj_dns_settings").blocklist_type("pj_dns_a_record").blocklist_type("pj_dns_addr_record").blocklist_type("pj_stun_sock")
        .blocklist_type("pj_stun_sock_cb").blocklist_type("pj_stun_sock_info").blocklist_type("pj_stun_sock_cfg").blocklist_type("pj_turn_session")
        .blocklist_type("pj_turn_channel_data").blocklist_type("pj_turn_session_cb").blocklist_type("pj_turn_alloc_param").blocklist_type("pj_turn_session_info")
        .blocklist_type("pj_turn_session_on_rx_pkt_param").blocklist_type("pj_turn_sock").blocklist_type("pj_turn_sock_cb").blocklist_type("pj_turn_sock_tls_cfg")
        .blocklist_type("pj_turn_sock_cfg").blocklist_type("pj_ice_strans").blocklist_type("pj_ice_strans_cb").blocklist_type("pj_ice_strans_stun_cfg")
        .blocklist_type("pj_ice_strans_turn_cfg").blocklist_type("pj_ice_strans_cfg").blocklist_type("pj_stun_nat_detect_result")




        .blocklist_type("pj_getopt_option").blocklist_type("pj_crc32_context").blocklist_type("pj_md5_context").blocklist_type("pj_hmac_md5_context")
        .blocklist_type("pj_sha1_context").blocklist_type("pj_hmac_sha1_context").blocklist_type("in6_addr__bindgen_ty_1").blocklist_type("pj_dns_hdr")
        .blocklist_type("pj_dns_parsed_query").blocklist_type("pj_dns_parsed_rr").blocklist_type("pj_dns_parsed_rr_rdata").blocklist_type("pj_dns_parsed_rr_rdata_srv")
        .blocklist_type("pj_dns_parsed_rr_rdata_cname").blocklist_type("pj_dns_parsed_rr_rdata_ns").blocklist_type("pj_dns_parsed_rr_rdata_ptr").blocklist_type("pj_dns_parsed_rr_rdata_a")
        .blocklist_type("pj_dns_parsed_rr_rdata_aaaa").blocklist_type("pj_dns_parsed_packet").blocklist_type("pj_dns_resolver").blocklist_type("pj_dns_async_query")
        .blocklist_type("pj_dns_settings").blocklist_type("pj_dns_a_record").blocklist_type("pj_dns_addr_record").blocklist_type("pj_dns_addr_record__bindgen_ty_1")
        .blocklist_type("pj_dns_addr_record__bindgen_ty_1__bindgen_ty_1").blocklist_type("pj_dns_srv_record").blocklist_type("pj_dns_srv_record__bindgen_ty_1").blocklist_type("pj_dns_srv_async_query")
        .blocklist_type("pj_dns_server").blocklist_type("pj_cis_buf_t").blocklist_type("pj_cis_t").blocklist_type("pj_scanner")
        .blocklist_type("pj_scan_state").blocklist_type("pj_xml_attr").blocklist_type("pj_xml_node_head").blocklist_type("pj_xml_node")
        .blocklist_type("pj_json_list").blocklist_type("pj_json_elem").blocklist_type("pj_json_elem__bindgen_ty_1").blocklist_type("pj_json_err_info")
        .blocklist_type("pjstun_msg_hdr").blocklist_type("pjstun_attr_hdr").blocklist_type("pjstun_msg").blocklist_type("pjstun_setting")
        .blocklist_type("pj_pcap_udp_hdr").blocklist_type("pj_pcap_filter").blocklist_type("pj_pcap_file").blocklist_type("pj_http_req")
        .blocklist_type("pj_http_header_elmt")
        .blocklist_type("pj_http_headers")
        .blocklist_type("pj_http_auth_cred")
        .blocklist_type("pj_http_req_param")
        .blocklist_type("pj_http_req_param_pj_http_reqdata")
        .blocklist_type("pj_http_auth_chal")
        .blocklist_type("pj_http_resp")
        .blocklist_type("pj_http_url")
        .blocklist_type("pj_http_req_callback")
        .blocklist_type("pj_cli_t")
        .blocklist_type("pj_cli_cfg")
        .blocklist_type("pj_cli_cmd_spec")
        .blocklist_type("pj_cli_cmd_val")
        .blocklist_type("pj_cli_hint_info")
        .blocklist_type("pj_cli_exec_info")
        .blocklist_type("pj_cli_arg_choice_val")
        .blocklist_type("pj_cli_dyn_choice_param")
        .blocklist_type("pj_cli_front_end_op")
        .blocklist_type("pj_cli_front_end")
        .blocklist_type("pj_cli_sess_op")
        .blocklist_type("pj_cli_sess")
        .blocklist_type("pj_cli_console_cfg")
        .blocklist_type("pj_cli_telnet_info")
        .blocklist_type("pj_cli_telnet_cfg")

        .allowlist_function("pjpidf_create")
        .allowlist_function("pjpidf_parse")
        .allowlist_function("pjpidf_pres_add_note")
        .allowlist_function("pjpidf_pres_add_tuple")
        .allowlist_function("pjpidf_pres_construct")
        .allowlist_function("pjpidf_pres_find_tuple")
        .allowlist_function("pjpidf_pres_get_first_note")
        .allowlist_function("pjpidf_pres_get_first_tuple")
        .allowlist_function("pjpidf_pres_get_next_note")
        .allowlist_function("pjpidf_pres_get_next_tuple")
        .allowlist_function("pjpidf_pres_remove_tuple")
        .allowlist_function("pjpidf_print")
        .allowlist_function("pjpidf_status_construct")
        .allowlist_function("pjpidf_status_is_basic_open")
        .allowlist_function("pjpidf_status_set_basic_open")
        .allowlist_function("pjpidf_tuple_add_note")
        .allowlist_function("pjpidf_tuple_construct")
        .allowlist_function("pjpidf_tuple_get_contact")
        .allowlist_function("pjpidf_tuple_get_contact_prio")
        .allowlist_function("pjpidf_tuple_get_first_note")
        .allowlist_function("pjpidf_tuple_get_id")
        .allowlist_function("pjpidf_tuple_get_next_note")
        .allowlist_function("pjpidf_tuple_get_status")
        .allowlist_function("pjpidf_tuple_get_timestamp")
        .allowlist_function("pjpidf_tuple_set_contact")
        .allowlist_function("pjpidf_tuple_set_contact_prio")
        .allowlist_function("pjpidf_tuple_set_id")
        .allowlist_function("pjpidf_tuple_set_timestamp")
        .allowlist_function("pjpidf_tuple_set_timestamp_np")
        .allowlist_function("pjrpid_add_element")
        .allowlist_function("pjrpid_element_dup")
        .allowlist_function("pjrpid_get_element")
        .allowlist_function("pjsip_allow_events_hdr_create")
        .allowlist_function("pjsip_event_hdr_create")
        .allowlist_function("pjsip_evsub_accept")
        .allowlist_function("pjsip_evsub_add_header")
        .allowlist_function("pjsip_evsub_add_ref")
        .allowlist_function("pjsip_evsub_create_uac")
        .allowlist_function("pjsip_evsub_create_uas")
        .allowlist_function("pjsip_evsub_current_notify")
        .allowlist_function("pjsip_evsub_dec_ref")
        .allowlist_function("pjsip_evsub_get_allow_events_hdr")
        .allowlist_function("pjsip_evsub_get_mod_data")
        .allowlist_function("pjsip_evsub_get_state")
        .allowlist_function("pjsip_evsub_get_state_name")
        .allowlist_function("pjsip_evsub_get_termination_reason")
        .allowlist_function("pjsip_evsub_initiate")
        .allowlist_function("pjsip_evsub_init_module")
        .allowlist_function("pjsip_evsub_init_parser")
        .allowlist_function("pjsip_evsub_instance")
        .allowlist_function("pjsip_evsub_notify")
        .allowlist_function("pjsip_evsub_register_pkg")
        .allowlist_function("pjsip_evsub_send_request")
        .allowlist_function("pjsip_evsub_set_mod_data")
        .allowlist_function("pjsip_evsub_terminate")
        .allowlist_function("pjsip_evsub_uas_set_timeout")
        .allowlist_function("pjsip_get_notify_method")
        .allowlist_function("pjsip_get_subscribe_method")
        .allowlist_function("pjsip_iscomposing_create_body")
        .allowlist_function("pjsip_iscomposing_create_xml")
        .allowlist_function("pjsip_iscomposing_parse")
        .allowlist_function("pjsip_mwi_accept")
        .allowlist_function("pjsip_mwi_create_uac")
        .allowlist_function("pjsip_mwi_create_uas")
        .allowlist_function("pjsip_mwi_current_notify")
        .allowlist_function("pjsip_mwi_initiate")
        .allowlist_function("pjsip_mwi_init_module")
        .allowlist_function("pjsip_mwi_instance")
        .allowlist_function("pjsip_mwi_notify")
        .allowlist_function("pjsip_mwi_send_request")
        .allowlist_function("pjsip_mwi_terminate")
        .allowlist_function("pjsip_pres_accept")
        .allowlist_function("pjsip_pres_add_header")
        .allowlist_function("pjsip_pres_create_pidf")
        .allowlist_function("pjsip_pres_create_uac")
        .allowlist_function("pjsip_pres_create_uas")
        .allowlist_function("pjsip_pres_create_xpidf")
        .allowlist_function("pjsip_pres_current_notify")
        .allowlist_function("pjsip_pres_get_status")
        .allowlist_function("pjsip_pres_initiate")
        .allowlist_function("pjsip_pres_init_module")
        .allowlist_function("pjsip_pres_instance")
        .allowlist_function("pjsip_pres_notify")
        .allowlist_function("pjsip_pres_parse_pidf")
        .allowlist_function("pjsip_pres_parse_pidf2")
        .allowlist_function("pjsip_pres_parse_xpidf")
        .allowlist_function("pjsip_pres_parse_xpidf2")
        .allowlist_function("pjsip_pres_send_request")
        .allowlist_function("pjsip_pres_set_status")
        .allowlist_function("pjsip_pres_terminate")
        .allowlist_function("pjsip_publishc_create")
        .allowlist_function("pjsip_publishc_destroy")
        .allowlist_function("pjsip_publishc_get_pool")
        .allowlist_function("pjsip_publishc_init")
        .allowlist_function("pjsip_publishc_init_module")
        .allowlist_function("pjsip_publishc_opt_default")
        .allowlist_function("pjsip_publishc_publish")
        .allowlist_function("pjsip_publishc_send")
        .allowlist_function("pjsip_publishc_set_credentials")
        .allowlist_function("pjsip_publishc_set_headers")
        .allowlist_function("pjsip_publishc_set_route_set")
        .allowlist_function("pjsip_publishc_set_via_sent_by")
        .allowlist_function("pjsip_publishc_unpublish")
        .allowlist_function("pjsip_publishc_update_expires")
        .allowlist_function("pjsipsimple_strerror")
        .allowlist_function("pjsip_sub_state_hdr_create")
        .allowlist_function("pjsip_tsx_get_evsub")
        .allowlist_function("pjxpidf_create")
        .allowlist_function("pjxpidf_get_status")
        .allowlist_function("pjxpidf_get_uri")
        .allowlist_function("pjxpidf_parse")
        .allowlist_function("pjxpidf_print")
        .allowlist_function("pjxpidf_set_status")
        .allowlist_function("pjxpidf_set_uri")

        .allowlist_var("pjpidf_op")
        .allowlist_var("pjsip_notify_method")
        .allowlist_var("pjsip_publish_method")
        .allowlist_var("pjsip_subscribe_method")

        // .allowlist_type("PJ.*")
        // .allowlist_type("pj.*")
        // .allowlist_function("PJ.*")
        // .allowlist_function("pj.*")
        // .allowlist_var("PJ.*")
        // .allowlist_var("pj.*")
        .allowlist_recursively(true)
        .translate_enum_integer_types(true)
        .layout_tests(false)
        .prepend_enum_name(false)
        .generate()
        // Unwrap the Result and panic on failure.
        .expect("Unable to generate bindings");

    // Write the bindings to the $OUT_DIR/bindings.rs file.
    let out_path = env::current_dir().unwrap();
    pjsip_simple.write_to_file(out_path.join("src/lib.rs")).expect("Error write src/lib.rs");

}
