
extern crate bindgen;
use std::env;


fn main () {

    println!("cargo:rustc-link-lib=pjsip");
    println!("cargo:rustc-link-search=native=/usr/lib");
    println!("cargo:rerun-if-changed=wrapper.h");

    let pjsip = bindgen::Builder::default().header("wrapper.h")

        .raw_line("#![allow(non_upper_case_globals)]")
        .raw_line("#![allow(non_camel_case_types)]")
        .raw_line("#![allow(non_snake_case)]")
        .raw_line("extern crate pj_sys;")
        .raw_line("extern crate pjlib_util_sys;")
        .raw_line("extern crate pjmedia_sys;")
        .raw_line("use pj_sys::*;")
        .raw_line("use pjlib_util_sys::*;")
        .raw_line("use pjmedia_sys::*;")
        // .parse_callbacks(Box::new(bindgen::CargoCallbacks))

        // pj-sys
        // struct
        .blocklist_type("pj_timestamp").blocklist_type("pj_sockaddr").blocklist_type("pj_str_t").blocklist_type("pj_timestamp__bindgen_ty_1")
        .blocklist_type("pj_hash_table_t").blocklist_type("pj_hash_entry").blocklist_type("pj_hash_iterator_t").blocklist_type("pj_ioqueue_t")
        .blocklist_type("pj_ioqueue_key_t").blocklist_type("pj_timer_heap_t").blocklist_type("pj_atomic_t").blocklist_type("pj_thread_t")
        .blocklist_type("pj_lock_t").blocklist_type("pj_grp_lock_t").blocklist_type("pj_mutex_t").blocklist_type("pj_sem_t")
        .blocklist_type("pj_event_t").blocklist_type("pj_pipe_t").blocklist_type("pj_time_val").blocklist_type("pj_parsed_time")
        .blocklist_type("pj_ioqueue_op_key_t").blocklist_type("pj_ioqueue_callback").blocklist_type("__sigset_t").blocklist_type("in_addr.*")
        .blocklist_type("in6_addr.*").blocklist_type("pj_sockaddr_in").blocklist_type("pj_sockaddr_in6").blocklist_type("pj_addr_hdr")
        .blocklist_type("pj_ip_mreq").blocklist_type("pj_sockopt_params").blocklist_type("pj_sockopt_params__bindgen_ty_1").blocklist_type("pj_activesock_t")
        .blocklist_type("pj_activesock_cb").blocklist_type("pj_activesock_cfg").blocklist_type("pj_hostent").blocklist_type("pj_addrinfo")
        .blocklist_type("__jmp_buf_tag").blocklist_type("pj_exception_state_t").blocklist_type("pj_fifobuf_t").blocklist_type("pj_file_stat")
        .blocklist_type("pj_ip_route_entry__bindgen_ty_1").blocklist_type("pj_enum_ip_option").blocklist_type("pj_list").blocklist_type("pj_grp_lock_config")
        .blocklist_type("pj_math_stat").blocklist_type("pj_sys_info").blocklist_type("pj_symbianos_params").blocklist_type("pj_rwmutex_t")
        .blocklist_type("pj_pool_block").blocklist_type("pj_pool_t").blocklist_type("pj_pool_factory_policy").blocklist_type("pj_pool_factory")
        .blocklist_type("pj_caching_pool").blocklist_type("pj_rbtree_node").blocklist_type("pj_rbtree").blocklist_type("pj_qos_params")
        .blocklist_type("pj_fd_set_t").blocklist_type("pj_ssl_sock_t").blocklist_type("pj_ssl_cert_t").blocklist_type("pj_ssl_cert_info")
        .blocklist_type("pj_ssl_cert_info__bindgen_ty_1").blocklist_type("pj_ssl_cert_info__bindgen_ty_2").blocklist_type("pj_ssl_cert_info__bindgen_ty_3").blocklist_type("pj_ssl_cert_info__bindgen_ty_4")
        .blocklist_type("pj_ssl_cert_info__bindgen_ty_4__bindgen_ty_1").blocklist_type("pj_ssl_cert_info__bindgen_ty_5").blocklist_type("pj_ssl_sock_cb").blocklist_type("pj_ssl_sock_info")
        .blocklist_type("pj_ssl_sock_param").blocklist_type("pj_ssl_start_connect_param").blocklist_type("pj_timer_entry").blocklist_type("__va_list_tag")

        // pj-sys
        // type
        .blocklist_type("pj_int64_t").blocklist_type("pj_uint64_t").blocklist_type("size_t").blocklist_type("pj_int32_t").blocklist_type("pj_uint32_t")
        .blocklist_type("pj_int16_t").blocklist_type("pj_uint16_t").blocklist_type("pj_int8_t").blocklist_type("pj_uint8_t").blocklist_type("pj_size_t")
        .blocklist_type("pj_ssize_t").blocklist_type("pj_status_t").blocklist_type("pj_bool_t").blocklist_type("pj_char_t").blocklist_type("pj_constants_")
        .blocklist_type("pj_off_t").blocklist_type("pj_list_type").blocklist_type("pj_atomic_value_t").blocklist_type("pj_oshandle_t").blocklist_type("pj_sock_t")
        .blocklist_type("pj_sockaddr_t").blocklist_type("pj_color_t").blocklist_type("pj_exception_id_t").blocklist_type("pj_exit_callback").blocklist_type("pj_ioqueue_operation_e")
        .blocklist_type("__uint8_t").blocklist_type("__uint16_t").blocklist_type("__uint32_t").blocklist_type("in_addr_t").blocklist_type("pj_socket_sd_type")
        .blocklist_type("pj_in_addr").blocklist_type("pj_in6_addr").blocklist_type("pj_os_err_type").blocklist_type("va_list").blocklist_type("pj_error_callback")
        .blocklist_type("__jmp_buf").blocklist_type("jmp_buf").blocklist_type("pj_jmp_buf").blocklist_type("pj_log_decoration").blocklist_type("pj_log_func")
        .blocklist_type("pj_file_access").blocklist_type("pj_file_seek_type").blocklist_type("pj_hash_entry_buf").blocklist_type("pj_highprec_t").blocklist_type("pj_sys_info_flag")
        .blocklist_type("pj_thread_create_flags").blocklist_type("pj_thread_proc").blocklist_type("pj_thread_desc").blocklist_type("pj_mutex_type_e").blocklist_type("pj_main_func_ptr")
        .blocklist_type("pj_pool_callback").blocklist_type("pj_rbcolor_t").blocklist_type("pj_rbtree_comp").blocklist_type("pj_qos_type").blocklist_type("pj_qos_flag")
        .blocklist_type("pj_qos_wmm_prio").blocklist_type("pj_ssl_cert_verify_flag_t").blocklist_type("pj_ssl_cert_name_type").blocklist_type("pj_ssl_cert_buffer").blocklist_type("pj_ssl_cipher")
        .blocklist_type("pj_ssl_curve").blocklist_type("pj_ssl_entropy").blocklist_type("pj_ssl_sock_proto").blocklist_type("pj_timer_id_t").blocklist_type("pj_timer_heap_callback")
        .blocklist_type("__builtin_va_list")

        // pj-sys
        // pub static
        .blocklist_item("PJ_VERSION").blocklist_item("PJ_AF_UNSPEC").blocklist_item("PJ_AF_UNIX").blocklist_item("PJ_AF_INET").blocklist_item("PJ_AF_INET6")
        .blocklist_item("PJ_AF_PACKET").blocklist_item("PJ_AF_IRDA").blocklist_item("PJ_SOCK_STREAM").blocklist_item("PJ_SOCK_DGRAM").blocklist_item("PJ_SOCK_RAW")
        .blocklist_item("PJ_SOCK_RDM").blocklist_item("PJ_SOL_SOCKET").blocklist_item("PJ_SOL_IP").blocklist_item("PJ_SOL_TCP").blocklist_item("PJ_SOL_UDP")
        .blocklist_item("PJ_SOL_IPV6").blocklist_item("PJ_IP_TOS").blocklist_item("PJ_IPTOS_LOWDELAY").blocklist_item("PJ_IPTOS_THROUGHPUT").blocklist_item("PJ_IPTOS_RELIABILITY")
        .blocklist_item("PJ_IPTOS_MINCOST").blocklist_item("PJ_IPV6_TCLASS").blocklist_item("PJ_SO_TYPE").blocklist_item("PJ_SO_RCVBUF").blocklist_item("PJ_SO_SNDBUF")
        .blocklist_item("PJ_TCP_NODELAY").blocklist_item("PJ_SO_REUSEADDR").blocklist_item("PJ_SO_NOSIGPIPE").blocklist_item("PJ_SO_PRIORITY").blocklist_item("PJ_IP_MULTICAST_IF")
        .blocklist_item("PJ_IP_MULTICAST_TTL").blocklist_item("PJ_IP_MULTICAST_LOOP").blocklist_item("PJ_IP_ADD_MEMBERSHIP").blocklist_item("PJ_IP_DROP_MEMBERSHIP").blocklist_item("PJ_MSG_OOB")
        .blocklist_item("PJ_MSG_PEEK").blocklist_item("PJ_MSG_DONTROUTE").blocklist_item("PJ_GUID_STRING_LENGTH").blocklist_item("pj_pool_factory_default_policy")

        .blocklist_item("pj_ssl_entropy").blocklist_item("pj_ssl_entropy_t")

        // pjlib-util-sys
        .blocklist_type("pj_dns_type")
        .blocklist_type("pj_dns_callback")
        .blocklist_type("pj_dns_srv_resolver_cb")
        .blocklist_type("pj_cis_elem_t")
        .blocklist_type("pj_syn_err_func_ptr")
        .blocklist_type("pj_json_val_type")
        .blocklist_type("pj_json_writer")
        .blocklist_type("pjstun_attr_type")
        .blocklist_type("pj_pcap_link_type")
        .blocklist_type("pj_pcap_proto_type")
        .blocklist_type("pj_cli_cmd_id")
        .blocklist_type("pj_cli_arg_id")
        .blocklist_type("pj_cli_get_dyn_choice")
        .blocklist_type("pj_cli_cmd_handler")
        .blocklist_type("pj_cli_front_end_type")
        .blocklist_type("pj_cli_telnet_on_started")



        // pjnath-sys
        // pub type
        .blocklist_type("pj_stun_method_e").blocklist_type("pj_stun_msg_class_e").blocklist_type("pj_stun_msg_type").blocklist_type("pj_stun_attr_type")
        .blocklist_type("pj_stun_status").blocklist_type("pj_stun_fingerprint_attr").blocklist_type("pj_stun_realm_attr").blocklist_type("pj_stun_nonce_attr")
        .blocklist_type("pj_stun_mapped_addr_attr").blocklist_type("pj_stun_xor_mapped_addr_attr").blocklist_type("pj_stun_software_attr").blocklist_type("pj_stun_alt_server_attr")
        .blocklist_type("pj_stun_refresh_interval_attr").blocklist_type("pj_stun_response_addr_attr").blocklist_type("pj_stun_changed_addr_attr").blocklist_type("pj_stun_change_request_attr")
        .blocklist_type("pj_stun_src_addr_attr").blocklist_type("pj_stun_reflected_from_attr").blocklist_type("pj_stun_username_attr").blocklist_type("pj_stun_password_attr")
        .blocklist_type("pj_stun_channel_number_attr").blocklist_type("pj_stun_lifetime_attr").blocklist_type("pj_stun_bandwidth_attr").blocklist_type("pj_stun_xor_peer_addr_attr")
        .blocklist_type("pj_stun_data_attr").blocklist_type("pj_stun_xor_relayed_addr_attr").blocklist_type("pj_stun_req_addr_type_attr").blocklist_type("pj_stun_even_port_attr")
        .blocklist_type("pj_stun_req_transport_attr").blocklist_type("pj_stun_dont_fragment_attr").blocklist_type("pj_stun_res_token_attr").blocklist_type("pj_stun_xor_reflected_from_attr")
        .blocklist_type("pj_stun_priority_attr").blocklist_type("pj_stun_use_candidate_attr").blocklist_type("pj_stun_timer_val_attr").blocklist_type("pj_stun_ice_controlling_attr")
        .blocklist_type("pj_stun_ice_controlled_attr").blocklist_type("pj_stun_icmp_attr").blocklist_type("pj_stun_decode_options").blocklist_type("pj_stun_auth_type")
        .blocklist_type("pj_stun_auth_cred_type").blocklist_type("pj_stun_passwd_type").blocklist_type("pj_stun_sess_msg_log_flag").blocklist_type("pj_ice_cand_type")
        .blocklist_type("pj_ice_sess_check_state").blocklist_type("pj_ice_sess_checklist_state").blocklist_type("pj_ice_sess_role").blocklist_type("pj_ice_sess_trickle")
        .blocklist_type("pj_dns_rcode").blocklist_type("pj_dns_dup_options").blocklist_type("pj_stun_sock_op").blocklist_type("pj_turn_tp_type")
        .blocklist_type("pj_turn_state_t").blocklist_type("pj_ice_strans_op").blocklist_type("pj_ice_strans_state").blocklist_type("pj_stun_nat_type")
        .blocklist_type("pj_stun_nat_detect_cb")

        // pjnath-sys
        // pub struct
        .blocklist_type("pj_stun_msg_hdr").blocklist_type("pj_stun_attr_hdr").blocklist_type("pj_stun_sockaddr_attr").blocklist_type("pj_stun_empty_attr")
        .blocklist_type("pj_stun_string_attr").blocklist_type("pj_stun_uint_attr").blocklist_type("pj_stun_uint64_attr").blocklist_type("pj_stun_binary_attr")
        .blocklist_type("pj_stun_msgint_attr").blocklist_type("pj_stun_errcode_attr").blocklist_type("pj_stun_unknown_attr").blocklist_type("pj_stun_msg")
        .blocklist_type("pj_stun_auth_cred").blocklist_type("pj_stun_req_cred_info").blocklist_type("pj_stun_config").blocklist_type("pj_stun_client_tsx")
        .blocklist_type("pj_stun_tsx_cb").blocklist_type("pj_stun_session").blocklist_type("pj_stun_session_cb").blocklist_type("pj_stun_rx_data")
        .blocklist_type("pj_stun_tx_data").blocklist_type("pj_ice_sess_comp").blocklist_type("pj_ice_msg_data").blocklist_type("pj_ice_msg_data_data_request_data")
        .blocklist_type("pj_ice_sess_cand").blocklist_type("pj_ice_sess_check").blocklist_type("pj_ice_sess_checklist").blocklist_type("pj_ice_sess_cb")
        .blocklist_type("pj_ice_rx_check").blocklist_type("pj_ice_sess_options").blocklist_type("pj_ice_sess").blocklist_type("pj_dns_hdr")
        .blocklist_type("pj_dns_parsed_query").blocklist_type("pj_dns_parsed_rr").blocklist_type("pj_dns_parsed_rr_rdata").blocklist_type("pj_dns_parsed_rr_rdata_srv")
        .blocklist_type("pj_dns_parsed_rr_rdata_cname").blocklist_type("pj_dns_parsed_rr_rdata_ns").blocklist_type("pj_dns_parsed_rr_rdata_ptr").blocklist_type("pj_dns_parsed_rr_rdata_a")
        .blocklist_type("pj_dns_parsed_rr_rdata_aaaa").blocklist_type("pj_dns_parsed_packet").blocklist_type("pj_dns_resolver").blocklist_type("pj_dns_async_query")
        .blocklist_type("pj_dns_settings").blocklist_type("pj_dns_a_record").blocklist_type("pj_dns_addr_record").blocklist_type("pj_stun_sock")
        .blocklist_type("pj_stun_sock_cb").blocklist_type("pj_stun_sock_info").blocklist_type("pj_stun_sock_cfg").blocklist_type("pj_turn_session")
        .blocklist_type("pj_turn_channel_data").blocklist_type("pj_turn_session_cb").blocklist_type("pj_turn_alloc_param").blocklist_type("pj_turn_session_info")
        .blocklist_type("pj_turn_session_on_rx_pkt_param").blocklist_type("pj_turn_sock").blocklist_type("pj_turn_sock_cb").blocklist_type("pj_turn_sock_tls_cfg")
        .blocklist_type("pj_turn_sock_cfg").blocklist_type("pj_ice_strans").blocklist_type("pj_ice_strans_cb").blocklist_type("pj_ice_strans_stun_cfg")
        .blocklist_type("pj_ice_strans_turn_cfg").blocklist_type("pj_ice_strans_cfg").blocklist_type("pj_stun_nat_detect_result")

        .blocklist_type("pj_stun_msg_hdr").blocklist_type("pj_stun_attr_hdr").blocklist_type("pj_stun_sockaddr_attr").blocklist_type("pj_stun_empty_attr")
        .blocklist_type("pj_stun_string_attr").blocklist_type("pj_stun_uint_attr").blocklist_type("pj_stun_uint64_attr").blocklist_type("pj_stun_binary_attr")
        .blocklist_type("pj_stun_msgint_attr").blocklist_type("pj_stun_errcode_attr").blocklist_type("pj_stun_unknown_attr").blocklist_type("pj_stun_msg")
        .blocklist_type("pj_stun_auth_cred").blocklist_type("pj_stun_auth_cred__bindgen_ty_1").blocklist_type("pj_stun_auth_cred__bindgen_ty_1__bindgen_ty_1").blocklist_type("pj_stun_auth_cred__bindgen_ty_1__bindgen_ty_2")
        .blocklist_type("pj_stun_req_cred_info").blocklist_type("pj_stun_config").blocklist_type("pj_stun_client_tsx").blocklist_type("pj_stun_tsx_cb")
        .blocklist_type("pj_stun_session").blocklist_type("pj_stun_session_cb").blocklist_type("pj_stun_rx_data").blocklist_type("pj_stun_tx_data")
        .blocklist_type("pj_ice_sess_comp").blocklist_type("pj_ice_msg_data").blocklist_type("pj_ice_msg_data_data_request_data").blocklist_type("pj_ice_sess_cand")
        .blocklist_type("pj_ice_sess_check").blocklist_type("pj_ice_sess_checklist").blocklist_type("pj_ice_sess_cb").blocklist_type("pj_ice_rx_check")
        .blocklist_type("pj_ice_sess_options").blocklist_type("pj_ice_sess").blocklist_type("pj_dns_hdr").blocklist_type("pj_dns_parsed_query")
        .blocklist_type("pj_dns_parsed_rr").blocklist_type("pj_dns_parsed_rr_rdata").blocklist_type("pj_dns_parsed_rr_rdata_srv").blocklist_type("pj_dns_parsed_rr_rdata_cname")
        .blocklist_type("pj_dns_parsed_rr_rdata_ns").blocklist_type("pj_dns_parsed_rr_rdata_ptr").blocklist_type("pj_dns_parsed_rr_rdata_a").blocklist_type("pj_dns_parsed_rr_rdata_aaaa")
        .blocklist_type("pj_dns_parsed_packet").blocklist_type("pj_dns_resolver").blocklist_type("pj_dns_async_query").blocklist_type("pj_dns_settings")
        .blocklist_type("pj_dns_a_record").blocklist_type("pj_dns_addr_record").blocklist_type("pj_dns_addr_record__bindgen_ty_1").blocklist_type("pj_dns_addr_record__bindgen_ty_1__bindgen_ty_1")
        .blocklist_type("pj_stun_sock").blocklist_type("pj_stun_sock_cb").blocklist_type("pj_stun_sock_info").blocklist_type("pj_stun_sock_cfg")
        .blocklist_type("pj_turn_session").blocklist_type("pj_turn_channel_data").blocklist_type("pj_turn_session_cb").blocklist_type("pj_turn_alloc_param")
        .blocklist_type("pj_turn_session_info").blocklist_type("pj_turn_session_on_rx_pkt_param").blocklist_type("pj_turn_sock").blocklist_type("pj_turn_sock_cb")
        .blocklist_type("pj_turn_sock_tls_cfg").blocklist_type("pj_turn_sock_cfg").blocklist_type("pj_ice_strans").blocklist_type("pj_ice_strans_cb")
        .blocklist_type("pj_ice_strans_stun_cfg").blocklist_type("pj_ice_strans_turn_cfg").blocklist_type("pj_ice_strans_cfg").blocklist_type("pj_ice_strans_cfg__bindgen_ty_1")
        .blocklist_type("pj_stun_nat_detect_result")

        .blocklist_type("pj_stun_auth_cred__bindgen_ty_1")
        .blocklist_type("pj_stun_auth_cred__bindgen_ty_1__bindgen_ty_1")
        .blocklist_type("pj_stun_auth_cred__bindgen_ty_1__bindgen_ty_2")
        .blocklist_type("pj_dns_addr_record__bindgen_ty_1")
        .blocklist_type("pj_dns_addr_record__bindgen_ty_1__bindgen_ty_1")
        .blocklist_type("pj_ice_strans_cfg__bindgen_ty_1")

        .blocklist_type("pj_ice_msg_data_data")
        .blocklist_type("pj_ice_sess__bindgen_ty_1")

        // pjlib-util-sys
        .blocklist_type("pj_dns_type")
        .blocklist_type("pj_dns_callback")
        .blocklist_type("pj_dns_srv_resolver_cb")
        .blocklist_type("pj_cis_elem_t")
        .blocklist_type("pj_syn_err_func_ptr")
        .blocklist_type("pj_json_val_type")
        .blocklist_type("pj_json_writer")
        .blocklist_type("pjstun_attr_type")
        .blocklist_type("pj_pcap_link_type")
        .blocklist_type("pj_pcap_proto_type")
        .blocklist_type("pj_cli_cmd_id")
        .blocklist_type("pj_cli_arg_id")
        .blocklist_type("pj_cli_get_dyn_choice")
        .blocklist_type("pj_cli_cmd_handler")
        .blocklist_type("pj_cli_front_end_type")
        .blocklist_type("pj_cli_telnet_on_started")

        .allowlist_function("create_uas_dialog")
        .allowlist_function("deinit_sip_parser")
        .allowlist_function("init_sip_parser")
        .allowlist_function("pjsip_accept_hdr_create")
        .allowlist_function("pjsip_accept_hdr_init")
        .allowlist_function("pjsip_allow_hdr_create")
        .allowlist_function("pjsip_allow_hdr_init")
        .allowlist_function("pjsip_auth_clt_clone")
        .allowlist_function("pjsip_auth_clt_deinit")
        .allowlist_function("pjsip_auth_clt_get_prefs")
        .allowlist_function("pjsip_auth_clt_init")
        .allowlist_function("pjsip_auth_clt_init_req")
        .allowlist_function("pjsip_auth_clt_pref_dup")
        .allowlist_function("pjsip_auth_clt_reinit_req")
        .allowlist_function("pjsip_auth_clt_set_credentials")
        .allowlist_function("pjsip_auth_clt_set_prefs")
        .allowlist_function("pjsip_auth_create_digest")
        .allowlist_function("pjsip_auth_deinit_parser")
        .allowlist_function("pjsip_auth_init_parser")
        .allowlist_function("pjsip_authorization_hdr_create")
        .allowlist_function("pjsip_auth_srv_challenge")
        .allowlist_function("pjsip_auth_srv_init")
        .allowlist_function("pjsip_auth_srv_init2")
        .allowlist_function("pjsip_auth_srv_verify")
        .allowlist_function("pjsip_calculate_branch_id")
        .allowlist_function("pjsip_cid_hdr_create")
        .allowlist_function("pjsip_cid_hdr_init")
        .allowlist_function("pjsip_clen_hdr_create")
        .allowlist_function("pjsip_clen_hdr_init")
        .allowlist_function("pjsip_clone_text_data")
        .allowlist_function("pjsip_concat_param_imp")
        .allowlist_function("pjsip_contact_hdr_create")
        .allowlist_function("pjsip_contact_hdr_init")
        .allowlist_function("pjsip_cred_info_cmp")
        .allowlist_function("pjsip_cred_info_dup")
        .allowlist_function("pjsip_cseq_hdr_create")
        .allowlist_function("pjsip_cseq_hdr_init")
        .allowlist_function("pjsip_ctype_hdr_create")
        .allowlist_function("pjsip_ctype_hdr_init")
        .allowlist_function("pjsip_dlg_add_usage")
        .allowlist_function("pjsip_dlg_create_request")
        .allowlist_function("pjsip_dlg_create_response")
        .allowlist_function("pjsip_dlg_create_uac")
        .allowlist_function("pjsip_dlg_create_uac2")
        .allowlist_function("pjsip_dlg_create_uas_and_inc_lock")
        .allowlist_function("pjsip_dlg_dec_lock")
        .allowlist_function("pjsip_dlg_dec_session")
        .allowlist_function("pjsip_dlg_fork")
        .allowlist_function("pjsip_dlg_get_lock")
        .allowlist_function("pjsip_dlg_get_mod_data")
        .allowlist_function("pjsip_dlg_get_remote_cap_hdr")
        .allowlist_function("pjsip_dlg_has_usage")
        .allowlist_function("pjsip_dlg_inc_lock")
        .allowlist_function("pjsip_dlg_inc_session")
        .allowlist_function("pjsip_dlg_modify_response")
        .allowlist_function("pjsip_dlg_on_rx_request")
        .allowlist_function("pjsip_dlg_on_rx_response")
        .allowlist_function("pjsip_dlg_on_tsx_state")
        .allowlist_function("pjsip_dlg_remote_has_cap")
        .allowlist_function("pjsip_dlg_remove_remote_cap_hdr")
        .allowlist_function("pjsip_dlg_respond")
        .allowlist_function("pjsip_dlg_send_request")
        .allowlist_function("pjsip_dlg_send_response")
        .allowlist_function("pjsip_dlg_set_mod_data")
        .allowlist_function("pjsip_dlg_set_remote_cap_hdr")
        .allowlist_function("pjsip_dlg_set_route_set")
        .allowlist_function("pjsip_dlg_set_transport")
        .allowlist_function("pjsip_dlg_set_via_sent_by")
        .allowlist_function("pjsip_dlg_terminate")
        .allowlist_function("pjsip_dlg_try_inc_lock")
        .allowlist_function("pjsip_dlg_update_remote_cap")
        .allowlist_function("pjsip_endpt_acquire_transport")
        .allowlist_function("pjsip_endpt_acquire_transport2")
        .allowlist_function("pjsip_endpt_add_capability")
        .allowlist_function("pjsip_endpt_atexit")
        .allowlist_function("pjsip_endpt_cancel_timer")
        .allowlist_function("pjsip_endpt_create")
        .allowlist_function("pjsip_endpt_create_ack")
        .allowlist_function("pjsip_endpt_create_cancel")
        .allowlist_function("pjsip_endpt_create_pool")
        .allowlist_function("pjsip_endpt_create_request")
        .allowlist_function("pjsip_endpt_create_request_from_hdr")
        .allowlist_function("pjsip_endpt_create_request_fwd")
        .allowlist_function("pjsip_endpt_create_resolver")
        .allowlist_function("pjsip_endpt_create_response")
        .allowlist_function("pjsip_endpt_create_response_fwd")
        .allowlist_function("pjsip_endpt_create_tdata")
        .allowlist_function("pjsip_endpt_destroy")
        .allowlist_function("pjsip_endpt_dump")
        .allowlist_function("pjsip_endpt_get_capability")
        .allowlist_function("pjsip_endpt_get_ioqueue")
        .allowlist_function("pjsip_endpt_get_request_headers")
        .allowlist_function("pjsip_endpt_get_resolver")
        .allowlist_function("pjsip_endpt_get_timer_heap")
        .allowlist_function("pjsip_endpt_get_tpmgr")
        .allowlist_function("pjsip_endpt_handle_events")
        .allowlist_function("pjsip_endpt_handle_events2")
        .allowlist_function("pjsip_endpt_has_capability")
        .allowlist_function("pjsip_endpt_log_error")
        .allowlist_function("pjsip_endpt_name")
        .allowlist_function("pjsip_endpt_process_rx_data")
        .allowlist_function("pjsip_endpt_register_module")
        .allowlist_function("pjsip_endpt_release_pool")
        .allowlist_function("pjsip_endpt_resolve")
        .allowlist_function("pjsip_endpt_respond")
        .allowlist_function("pjsip_endpt_respond_stateless")
        .allowlist_function("pjsip_endpt_schedule_timer_dbg")
        .allowlist_function("pjsip_endpt_schedule_timer_w_grp_lock_dbg")
        .allowlist_function("pjsip_endpt_send_raw")
        .allowlist_function("pjsip_endpt_send_raw_to_uri")
        .allowlist_function("pjsip_endpt_send_request")
        .allowlist_function("pjsip_endpt_send_request_stateless")
        .allowlist_function("pjsip_endpt_send_response")
        .allowlist_function("pjsip_endpt_send_response2")
        .allowlist_function("pjsip_endpt_set_ext_resolver")
        .allowlist_function("pjsip_endpt_set_resolver")
        .allowlist_function("pjsip_endpt_unregister_module")
        .allowlist_function("pjsip_event_str")
        .allowlist_function("pjsip_expires_hdr_create")
        .allowlist_function("pjsip_expires_hdr_init")
        .allowlist_function("pjsip_find_msg")
        .allowlist_function("pjsip_from_hdr_create")
        .allowlist_function("pjsip_from_hdr_init")
        .allowlist_function("pjsip_fromto_hdr_set_from")
        .allowlist_function("pjsip_fromto_hdr_set_to")
        .allowlist_function("pjsip_generic_array_hdr_create")
        .allowlist_function("pjsip_generic_array_hdr_init")
        .allowlist_function("pjsip_generic_int_hdr_create")
        .allowlist_function("pjsip_generic_int_hdr_init")
        .allowlist_function("pjsip_generic_string_hdr_create")
        .allowlist_function("pjsip_generic_string_hdr_init")
        .allowlist_function("pjsip_generic_string_hdr_init2")
        .allowlist_function("pjsip_get_ack_method")
        .allowlist_function("pjsip_get_bye_method")
        .allowlist_function("pjsip_get_cancel_method")
        .allowlist_function("pjsip_get_dest_info")
        .allowlist_function("pjsip_get_invite_method")
        .allowlist_function("pjsip_get_options_method")
        .allowlist_function("pjsip_get_register_method")
        .allowlist_function("pjsip_get_request_dest")
        .allowlist_function("pjsip_get_response_addr")
        .allowlist_function("pjsip_get_status_text")
        .allowlist_function("pjsip_hdr_clone")
        .allowlist_function("pjsip_hdr_print_on")
        .allowlist_function("pjsip_hdr_shallow_clone")
        .allowlist_function("pjsip_loop_set_delay")
        .allowlist_function("pjsip_loop_set_discard")
        .allowlist_function("pjsip_loop_set_failure")
        .allowlist_function("pjsip_loop_set_recv_delay")
        .allowlist_function("pjsip_loop_set_send_callback_delay")
        .allowlist_function("pjsip_loop_start")
        .allowlist_function("pjsip_max_fwd_hdr_create")
        .allowlist_function("pjsip_max_fwd_hdr_init")
        .allowlist_function("pjsip_media_type_cmp")
        .allowlist_function("pjsip_media_type_cp")
        .allowlist_function("pjsip_media_type_init")
        .allowlist_function("pjsip_media_type_init2")
        .allowlist_function("pjsip_media_type_print")
        .allowlist_function("pjsip_method_cmp")
        .allowlist_function("pjsip_method_copy")
        .allowlist_function("pjsip_method_creates_dialog")
        .allowlist_function("pjsip_method_init")
        .allowlist_function("pjsip_method_init_np")
        .allowlist_function("pjsip_method_set")
        .allowlist_function("pjsip_min_expires_hdr_create")
        .allowlist_function("pjsip_min_expires_hdr_init")
        .allowlist_function("pjsip_msg_body_clone")
        .allowlist_function("pjsip_msg_body_copy")
        .allowlist_function("pjsip_msg_body_create")
        .allowlist_function("pjsip_msg_clone")
        .allowlist_function("pjsip_msg_create")
        .allowlist_function("pjsip_msg_find_hdr")
        .allowlist_function("pjsip_msg_find_hdr_by_name")
        .allowlist_function("pjsip_msg_find_hdr_by_names")
        .allowlist_function("pjsip_msg_find_remove_hdr")
        .allowlist_function("pjsip_msg_print")
        .allowlist_function("pjsip_multipart_add_part")
        .allowlist_function("pjsip_multipart_clone_part")
        .allowlist_function("pjsip_multipart_create")
        .allowlist_function("pjsip_multipart_create_part")
        .allowlist_function("pjsip_multipart_find_part")
        .allowlist_function("pjsip_multipart_get_first_part")
        .allowlist_function("pjsip_multipart_get_next_part")
        .allowlist_function("pjsip_multipart_get_raw")
        .allowlist_function("pjsip_multipart_parse")
        .allowlist_function("pjsip_name_addr_assign")
        .allowlist_function("pjsip_name_addr_create")
        .allowlist_function("pjsip_name_addr_init")
        .allowlist_function("pjsip_other_uri_create")
        .allowlist_function("pjsip_param_clone")
        .allowlist_function("pjsip_param_cmp")
        .allowlist_function("pjsip_param_find")
        .allowlist_function("pjsip_param_print_on")
        .allowlist_function("pjsip_param_shallow_clone")
        .allowlist_function("pjsip_parse_end_hdr_imp")
        .allowlist_function("pjsip_parse_generic_array_hdr_imp")
        .allowlist_function("pjsip_parse_hdr")
        .allowlist_function("pjsip_parse_headers")
        .allowlist_function("pjsip_parse_msg")
        .allowlist_function("pjsip_parse_param_imp")
        .allowlist_function("pjsip_parser_const")
        .allowlist_function("pjsip_parse_rdata")
        .allowlist_function("pjsip_parse_status_line")
        .allowlist_function("pjsip_parse_uri")
        .allowlist_function("pjsip_parse_uri_param_imp")
        .allowlist_function("pjsip_print_text_body")
        .allowlist_function("pjsip_process_rdata_param_default")
        .allowlist_function("pjsip_process_route_set")
        .allowlist_function("pjsip_proxy_authenticate_hdr_create")
        .allowlist_function("pjsip_proxy_authorization_hdr_create")
        .allowlist_function("pjsip_rdata_get_dlg")
        .allowlist_function("pjsip_rdata_get_tsx")
        .allowlist_function("pjsip_register_hdr_parser")
        .allowlist_function("pjsip_register_uri_parser")
        .allowlist_function("pjsip_require_hdr_create")
        .allowlist_function("pjsip_require_hdr_init")
        .allowlist_function("pjsip_resolve")
        .allowlist_function("pjsip_resolver_create")
        .allowlist_function("pjsip_resolver_destroy")
        .allowlist_function("pjsip_resolver_get_resolver")
        .allowlist_function("pjsip_resolver_set_ext_resolver")
        .allowlist_function("pjsip_resolver_set_resolver")
        .allowlist_function("pjsip_restore_strict_route_set")
        .allowlist_function("pjsip_retry_after_hdr_create")
        .allowlist_function("pjsip_retry_after_hdr_init")
        .allowlist_function("pjsip_role_name")
        .allowlist_function("pjsip_route_hdr_create")
        .allowlist_function("pjsip_route_hdr_init")
        .allowlist_function("pjsip_routing_hdr_set_route")
        .allowlist_function("pjsip_routing_hdr_set_rr")
        .allowlist_function("pjsip_rr_hdr_create")
        .allowlist_function("pjsip_rr_hdr_init")
        .allowlist_function("pjsip_rx_data_clone")
        .allowlist_function("pjsip_rx_data_free_cloned")
        .allowlist_function("pjsip_rx_data_get_info")
        .allowlist_function("pjsip_sip_uri_assign")
        .allowlist_function("pjsip_sip_uri_create")
        .allowlist_function("pjsip_sip_uri_init")
        .allowlist_function("pjsip_sip_uri_set_secure")
        .allowlist_function("pjsip_strerror")
        .allowlist_function("pjsip_supported_hdr_create")
        .allowlist_function("pjsip_supported_hdr_init")
        .allowlist_function("pjsip_target_assign_status")
        .allowlist_function("pjsip_target_set_add_from_msg")
        .allowlist_function("pjsip_target_set_add_uri")
        .allowlist_function("pjsip_target_set_get_next")
        .allowlist_function("pjsip_target_set_set_current")
        .allowlist_function("pjsip_tcp_transport_cfg_default")
        .allowlist_function("pjsip_tcp_transport_get_socket")
        .allowlist_function("pjsip_tcp_transport_lis_start")
        .allowlist_function("pjsip_tcp_transport_restart")
        .allowlist_function("pjsip_tcp_transport_start")
        .allowlist_function("pjsip_tcp_transport_start2")
        .allowlist_function("pjsip_tcp_transport_start3")
        .allowlist_function("pjsip_tdata_get_dlg")
        .allowlist_function("pjsip_tel_nb_cmp")
        .allowlist_function("pjsip_tel_uri_create")
        .allowlist_function("pjsip_tel_uri_subsys_init")
        .allowlist_function("pjsip_tls_setting_wipe_keys")
        .allowlist_function("pjsip_tls_transport_lis_start")
        .allowlist_function("pjsip_tls_transport_restart")
        .allowlist_function("pjsip_tls_transport_start")
        .allowlist_function("pjsip_tls_transport_start2")
        .allowlist_function("pjsip_to_hdr_create")
        .allowlist_function("pjsip_to_hdr_init")
        .allowlist_function("pjsip_tpmgr_acquire_transport")
        .allowlist_function("pjsip_tpmgr_acquire_transport2")
        .allowlist_function("pjsip_tpmgr_create")
        .allowlist_function("pjsip_tpmgr_destroy")
        .allowlist_function("pjsip_tpmgr_dump_transports")
        .allowlist_function("pjsip_tpmgr_find_local_addr")
        .allowlist_function("pjsip_tpmgr_find_local_addr2")
        .allowlist_function("pjsip_tpmgr_fla2_param_default")
        .allowlist_function("pjsip_tpmgr_get_state_cb")
        .allowlist_function("pjsip_tpmgr_get_transport_count")
        .allowlist_function("pjsip_tpmgr_receive_packet")
        .allowlist_function("pjsip_tpmgr_register_tpfactory")
        .allowlist_function("pjsip_tpmgr_send_raw")
        .allowlist_function("pjsip_tpmgr_set_drop_data_cb")
        .allowlist_function("pjsip_tpmgr_set_state_cb")
        .allowlist_function("pjsip_tpmgr_unregister_tpfactory")
        .allowlist_function("pjsip_tpselector_add_ref")
        .allowlist_function("pjsip_tpselector_dec_ref")
        .allowlist_function("pjsip_transport_add_ref")
        .allowlist_function("pjsip_transport_add_state_listener")
        .allowlist_function("pjsip_transport_dec_ref")
        .allowlist_function("pjsip_transport_destroy")
        .allowlist_function("pjsip_transport_get_default_port_for_type")
        .allowlist_function("pjsip_transport_get_flag_from_type")
        .allowlist_function("pjsip_transport_get_type_desc")
        .allowlist_function("pjsip_transport_get_type_from_flag")
        .allowlist_function("pjsip_transport_get_type_from_name")
        .allowlist_function("pjsip_transport_get_type_name")
        .allowlist_function("pjsip_transport_register")
        .allowlist_function("pjsip_transport_register_type")
        .allowlist_function("pjsip_transport_remove_state_listener")
        .allowlist_function("pjsip_transport_send")
        .allowlist_function("pjsip_transport_shutdown")
        .allowlist_function("pjsip_transport_shutdown2")
        .allowlist_function("pjsip_transport_type_get_af")
        .allowlist_function("pjsip_tsx_create_key")
        .allowlist_function("pjsip_tsx_create_uac")
        .allowlist_function("pjsip_tsx_create_uac2")
        .allowlist_function("pjsip_tsx_create_uas")
        .allowlist_function("pjsip_tsx_create_uas2")
        .allowlist_function("pjsip_tsx_get_dlg")
        .allowlist_function("pjsip_tsx_layer_destroy")
        .allowlist_function("pjsip_tsx_layer_dump")
        .allowlist_function("pjsip_tsx_layer_find_tsx")
        .allowlist_function("pjsip_tsx_layer_find_tsx2")
        .allowlist_function("pjsip_tsx_layer_get_tsx_count")
        .allowlist_function("pjsip_tsx_layer_init_module")
        .allowlist_function("pjsip_tsx_layer_instance")
        .allowlist_function("pjsip_tsx_recv_msg")
        .allowlist_function("pjsip_tsx_retransmit_no_state")
        .allowlist_function("pjsip_tsx_send_msg")
        .allowlist_function("pjsip_tsx_set_timeout")
        .allowlist_function("pjsip_tsx_set_transport")
        .allowlist_function("pjsip_tsx_state_str")
        .allowlist_function("pjsip_tsx_stop_retransmit")
        .allowlist_function("pjsip_tsx_terminate")
        .allowlist_function("pjsip_tx_data_add_ref")
        .allowlist_function("pjsip_tx_data_clone")
        .allowlist_function("pjsip_tx_data_create")
        .allowlist_function("pjsip_tx_data_dec_ref")
        .allowlist_function("pjsip_tx_data_encode")
        .allowlist_function("pjsip_tx_data_get_info")
        .allowlist_function("pjsip_tx_data_invalidate_msg")
        .allowlist_function("pjsip_tx_data_is_valid")
        .allowlist_function("pjsip_tx_data_set_transport")
        .allowlist_function("pjsip_ua_destroy")
        .allowlist_function("pjsip_ua_dump")
        .allowlist_function("pjsip_ua_find_dialog")
        .allowlist_function("pjsip_ua_get_dlg_set_count")
        .allowlist_function("pjsip_ua_get_endpt")
        .allowlist_function("pjsip_ua_init_module")
        .allowlist_function("pjsip_ua_instance")
        .allowlist_function("pjsip_ua_register_dlg")
        .allowlist_function("pjsip_ua_unregister_dlg")
        .allowlist_function("pjsip_udp_transport_attach")
        .allowlist_function("pjsip_udp_transport_attach2")
        .allowlist_function("pjsip_udp_transport_cfg_default")
        .allowlist_function("pjsip_udp_transport_get_socket")
        .allowlist_function("pjsip_udp_transport_pause")
        .allowlist_function("pjsip_udp_transport_restart")
        .allowlist_function("pjsip_udp_transport_restart2")
        .allowlist_function("pjsip_udp_transport_start")
        .allowlist_function("pjsip_udp_transport_start2")
        .allowlist_function("pjsip_udp_transport_start6")
        .allowlist_function("pjsip_unsupported_hdr_create")
        .allowlist_function("pjsip_unsupported_hdr_init")
        .allowlist_function("pjsip_via_hdr_create")
        .allowlist_function("pjsip_via_hdr_init")
        .allowlist_function("pjsip_warning_hdr_create")
        .allowlist_function("pjsip_warning_hdr_create_from_status")
        .allowlist_function("pjsip_www_authenticate_hdr_create")

        .allowlist_var("mod_stateful_util")
        .allowlist_var("pjsip_ack_method")
        .allowlist_var("pjsip_ALGORITHM_STR")
        .allowlist_var("pjsip_AUTH_STR")
        .allowlist_var("pjsip_BEARER_STR")
        .allowlist_var("pjsip_bye_method")
        .allowlist_var("pjsip_cancel_method")
        .allowlist_var("pjsip_CNONCE_STR")
        .allowlist_var("pjsip_DIGEST_STR")
        .allowlist_var("pjsip_DOMAIN_STR")
        .allowlist_var("PJSIP_EINVAL_ERR_EXCEPTION")
        .allowlist_var("pjsip_FALSE_STR")
        .allowlist_var("pjsip_hdr_names")
        .allowlist_var("pjsip_include_allow_hdr_in_dlg")
        .allowlist_var("pjsip_invite_method")
        .allowlist_var("pjsip_MD5_STR")
        .allowlist_var("pjsip_NC_STR")
        .allowlist_var("pjsip_NONCE_STR")
        .allowlist_var("pjsip_OPAQUE_STR")
        .allowlist_var("pjsip_options_method")
        .allowlist_var("pjsip_PGP_STR")
        .allowlist_var("pjsip_QOP_STR")
        .allowlist_var("pjsip_QUOTED_AUTH_STR")
        .allowlist_var("pjsip_QUOTED_DIGEST_STR")
        .allowlist_var("pjsip_QUOTED_FALSE_STR")
        .allowlist_var("pjsip_QUOTED_MD5_STR")
        .allowlist_var("pjsip_QUOTED_PGP_STR")
        .allowlist_var("pjsip_QUOTED_TRUE_STR")
        .allowlist_var("pjsip_REALM_STR")
        .allowlist_var("pjsip_register_method")
        .allowlist_var("pjsip_RESPONSE_STR")
        .allowlist_var("pjsip_sip_cfg_var")
        .allowlist_var("pjsip_STALE_STR")
        .allowlist_var("PJSIP_SYN_ERR_EXCEPTION")
        .allowlist_var("pjsip_TRUE_STR")
        .allowlist_var("pjsip_URI_STR")
        .allowlist_var("pjsip_USERNAME_STR")

        // .whitelisted_type("PJSIP_.*")
        // .whitelisted_type("pjsip_.*")
        // .whitelisted_function("PJSIP_.*")
        // .whitelisted_function("pjsip_.*")
        // .whitelisted_var("PJSIP_.*")
        // .whitelisted_var("pjsip_.*")



        .allowlist_recursively(true)
        .translate_enum_integer_types(true)
        .layout_tests(false)
        .prepend_enum_name(false)
        .layout_tests(false)
        .generate()
        // Unwrap the Result and panic on failure.
        .expect("Unable to generate bindings");

    // Write the bindings to the $OUT_DIR/bindings.rs file.
    let out_path = env::current_dir().unwrap();
    pjsip.write_to_file(out_path.join("src/lib.rs")).expect("Error write src/lib.rs");

}
